import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'screens/splash_screen.dart';

import 'package:wakelock_plus/wakelock_plus.dart';

import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  WakelockPlus.enable();

  try {
    // Ideally use DefaultFirebaseOptions if generated by flutterfire configure
    // Since user manually added google-services.json, we can just call initializeApp() for Android
    await Firebase.initializeApp();
  } catch (e) {
    print("Firebase Init Error: $e");
  }

  runApp(const SmartPillBoxApp());
}

class SmartPillBoxApp extends StatelessWidget {
  const SmartPillBoxApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Pill Box',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF4A90E2),
          primary: const Color(0xFF4A90E2),
          secondary: const Color(0xFF002F6C),
        ),
        useMaterial3: true,
        textTheme: GoogleFonts.poppinsTextTheme(Theme.of(context).textTheme),
      ),
      home: const SplashScreen(),
    );
  }
}
